get_available_spots:
  fields:
    date:
      required: false
      example: "2025-12-25"
      selector:
        date:
release_parking_spot:
  fields:
    date:
      required: false
      example: "2025-12-25"
      selector:
        date:
reserve_parking_spot:
  fields:
    date:
      required: false
      example: "2025-12-25"
      selector:
        date:
    parking_id:
      required: false
      example: "123"
      selector:
        text:
          type: number
    preferred_spots:
      required: false
      example: "- floor: -4\n  - spot: 12"
      selector:
        object:

get_status:
  fields:
    date:
      required: false
      example: "2025-12-25"
      selector:
        date:
